apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-pvc
spec:
  volumeName: todo-pv
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi